### ISSUE TITLE
Small ed25519 python implementation

### ISSUE THREAD

**Issue by lontivero** [Marten4n6/TinyTor#3]
In the code I can read you don't use NTOR because openssl on MacOS:

https://github.com/Marten4n6/TinyTor/blob/4e1d611d25678a3231a82a8de5447aab0b10cbfc/tinytor.py#L544-L545

Probably you already know this but anyway, there is a small ed25519 implementation in pure python: 
http://ed25519.cr.yp.to/python/ed25519.py

This is also used in the official Tor project. You can see how the use it here: https://gitweb.torproject.org/tor.git/tree/src/test/ed25519_exts_ref.py

**Comment by Marten4n6** [comment]
I didn't know Ed25519 is both a signature scheme and a use case for Edwards-form Curve25519.
I thought ED25519 could only be used for signing...

I will look into switching to NTOR, thank you!

**Comment by Marten4n6** [comment]
The handshake is now working with NTOR (only need to add verification), thanks again.
